version: "3.1"

services:
  php:
    image: php:7.2-apache
    build: .
    volumes:
      - ./src:/var/www/html
    secrets:
      - qc_password
    environment:
      # QC Secrets
      - MY_QC_PASSWORD_FILE=/run/secrets/qc_password

secrets:  
  qc_password:
    file: /etc/secrets/secret.json
